#!/bin/bash
find . -type f -name "*.gif" -printf "%f\n" | sort -t. -k1,1f
~                                                                                                                                                                       
~                                                                                                                                                                       
~                                                           
