#!/usr/bin/env bash
# Displays information about users from the /etc/passwd file using the while loop + IFS
while IFS=: read -r user pass uid gid u_info home command; do
    echo -n "The user $user is part of the $gid gang. "
    echo -n "Lives in $home and rides $command. "
    echo -n "$uid's place is protected by passcode $pass. "
    echo "More info about the user: $u_info"
done < "/etc/passwd"
