#!/usr/bin/env bash
# displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=":" read -r username _ uid gid user_info home shell; do
    password=$(echo "$user_info" | awk -F ':' '{print $2}')
    user_id_info=$(echo "$user_info" | awk -F ':' '{print $5}')
  home_dir_part=$(basename "$home")
 home_dir_part=${home_dir_part%"$username"}
    group_info=$(getent group "$gid" | cut -d: -f1)

    echo "The user $username is part of the group $group_info gang, lives in $home_dir_part and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $user_id_info"
    echo
done < /etc/passwd
