#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data
awk '{ print $1, $9 }' apache-access.log \
  | awk '
       { count[$0]++ }
       END {
         for (key in count) {
           print count[key], key
         }
       }
     ' \
  | sort -rn \
  | awk '{ printf "%5d %s\n", $1, $2 }'
