#!/usr/bin/env bash
# Using a while loop with if, elif, and else statement
counter=1
while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "Bad Luck"
    elif [ $counter -eq 8 ]; then
        echo "Good Luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
