#!/usr/bin/env bash

# Function to handle SIGTERM and SIGQUIT signals
handle_signals() {
    echo "Deleting PID file and terminating..."
    rm -f /var/run/myscript.pid
    exit 0
}

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Trap signals
trap 'handle_signals' SIGQUIT SIGTERM
trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT

# Write PID to file
echo $$ > /var/run/myscript.pid

# Infinite loop
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
