#!/usr/bin/env bash

# Function to handle cleanup
clean_up() {
    echo "Cleaning up and terminating..."
    rm -f /var/run/myscript.pid
    exit $?
}

# Function to handle SIGINT signal
handle_sigint() {
    echo "Y U no love me?!"
}

# Function to handle SIGTERM signal
handle_sigterm() {
    echo "I hate the kill command"
}

# Register clean_up function to trap signals
trap 'clean_up' SIGTERM SIGQUIT
trap 'handle_sigint' SIGINT
trap 'handle_sigterm' SIGTERM

# Store the PID of this script
echo $$ > "/var/run/myscript.pid"

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done

