#!/usr/bin/env bash
# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
pid=$(pgrep "4-to_infinity_and_beyond")
if [ -n "$pid" ]; then
      kill "$pid"
    echo "4-to_infinity_and_beyond process has been stopped."
else
    echo "4-to_infinity_and_beyond process is not running."
fi
