#!/usr/bin/env bash
# stop the 4-to_infinity_and_beyond proccess without using kill or killall
# Run the process in the background
./4-to_infinity_and_beyond &

# Get the PID of the last background process
PID=$!

# Wait for the process to finish
wait $PID

# Output confirmation
echo "Process terminated"
