#!/usr/bin/env bash
# Trap SIGTERM signal
trap 'echo "I am invincible!!!"; pkill -TERM -f "7-highlander"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
