#!/sur/bin/env bash
# displays To infinity and beyond indefinitely
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond indefinitely"
    sleep 2
done
